### ISSUE TITLE
Error at loading

### ISSUE THREAD

**Issue by rcharre** [N6REJ/AdiBags_Shadowlands_Mining#12]
Hi,

I have those 9 errors after loading my UI : 
`Message: Interface/AddOns/AdiBags_Bears_Mining/locales.lua:4: '=' expected near 'local'
Time: Sat Oct 29 13:28:27 2022
Count: 1
Stack: Interface/AddOns/AdiBags_Bears_Mining/locales.lua:4: '=' expected near 'local'
Locals: `

`Message: Interface/AddOns/AdiBags_Bears_Mining/database.lua:9: attempt to index local 'L' (a nil value)
Time: Sat Oct 29 13:28:27 2022
Count: 1
Stack: Interface/AddOns/AdiBags_Bears_Mining/database.lua:9: attempt to index local 'L' (a nil value)
[string "@Interface/AddOns/AdiBags_Bears_Mining/database.lua"]:9: in main chunk

Locals: addonName = "AdiBags_Bears_Mining"
addonTable = <table> {
}
L = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'L' (a nil value)"`

`Message: Interface/AddOns/AdiBags_Bears_Mining/core.lua:98: attempt to index local 'db' (a nil value)
Time: Sat Oct 29 13:28:27 2022
Count: 1
Stack: Interface/AddOns/AdiBags_Bears_Mining/core.lua:98: attempt to index local 'db' (a nil value)
[string "@Interface/AddOns/AdiBags_Bears_Mining/core.lua"]:98: in function `AllFilters'
[string "@Interface/AddOns/AdiBags_Bears_Mining/core.lua"]:112: in main chunk

Locals: db = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'db' (a nil value)"
CheckFilter = <function> defined @Interface/AddOns/AdiBags_Bears_Mining/core.lua:41
CreateFilter = <function> defined @Interface/AddOns/AdiBags_Bears_Mining/core.lua:53
`

`Message: Interface/AddOns/AdiBags_Bears_Mining/locales.lua:1 Interface/AddOns/AdiBags_Bears_Mining/locales.lua:4: '=' expected near 'local'
Time: Sat Oct 29 13:28:33 2022
Count: 1`

`Message: Interface/AddOns/AdiBags_Bears_Mining/database.lua:1 (null)
Time: Sat Oct 29 13:28:33 2022
Count: 1`

`Message: Interface/AddOns/AdiBags_Bears_Mining/core.lua:1 (null)
Time: Sat Oct 29 13:28:33 2022
Count: 1`

`Message: Interface\FrameXML\Bindings.xml:1 Interface/AddOns/AdiBags_Bears_Mining/locales.lua:1 Interface/AddOns/AdiBags_Bears_Mining/locales.lua:4: '=' expected near 'local'
Time: Sat Oct 29 13:28:33 2022
Count: 1`

`Message: Interface\FrameXML\Bindings.xml:1 Interface/AddOns/AdiBags_Bears_Mining/database.lua:1 (null)
Time: Sat Oct 29 13:28:33 2022
Count: 1`

`Message: Interface\FrameXML\Bindings.xml:1 Interface/AddOns/AdiBags_Bears_Mining/core.lua:1 (null)
Time: Sat Oct 29 13:28:33 2022
Count: 1`

I got the same with your other addon for engineer. Here is my addon list :

![image](https://user-images.githubusercontent.com/41190819/198829123-eb58fa73-3b84-4a21-9399-415be232e654.png)

![image](https://user-images.githubusercontent.com/41190819/198829130-4466971e-82a5-4d47-b950-028c94542309.png)
![image](https://user-images.githubusercontent.com/41190819/198829146-07e9240c-092e-45a8-9737-acdc74f689a6.png)

![image](https://user-images.githubusercontent.com/41190819/198829153-fe958ae8-1de5-46a0-bf31-af1f65e5187c.png)
![image](https://user-images.githubusercontent.com/41190819/198829166-fe18c4af-76d4-4c09-9f25-1f0d85fd3643.png)
![image](https://user-images.githubusercontent.com/41190819/198829174-281adbe8-16dc-4284-ba7e-b3072a375e04.png)

Thanks :)

**Comment by N6REJ** [comment]
we're looking into it.. ty for reporting.

**Comment by N6REJ** [comment]
It should be fixed with version "2022.10.29.1"  Please let me know.

**Comment by rcharre** [comment]
Tanks for your reactivity :)
Here are the new errors :

```
Message: Interface/AddOns/AdiBags_Bears_Mining/database.lua:15: attempt to concatenate local 'Expansion' (a nil value)
Time: Sat Oct 29 14:57:30 2022
Count: 1
Stack: Interface/AddOns/AdiBags_Bears_Mining/database.lua:15: attempt to concatenate local 'Expansion' (a nil value)
[string "@Interface/AddOns/AdiBags_Bears_Mining/database.lua"]:15: in main chunk

Locals: addonName = "AdiBags_Bears_Mining"
addonTable = <table> {
 locales = <table> {
 }
}
L = <table> {
 All = "All"
}
Expansion = nil
db = <table> {
 name = "Bears Mining"
}
(*temporary) = "Mining reagents for "
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to concatenate local 'Expansion' (a nil value)"
```

```
Message: Interface/AddOns/AdiBags_Bears_Mining/core.lua:97: attempt to index local 'db' (a nil value)
Time: Sat Oct 29 14:57:30 2022
Count: 1
Stack: Interface/AddOns/AdiBags_Bears_Mining/core.lua:97: attempt to index local 'db' (a nil value)
[string "@Interface/AddOns/AdiBags_Bears_Mining/core.lua"]:97: in function `AllFilters'
[string "@Interface/AddOns/AdiBags_Bears_Mining/core.lua"]:111: in main chunk

Locals: db = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'db' (a nil value)"
CheckFilter = <function> defined @Interface/AddOns/AdiBags_Bears_Mining/core.lua:40
CreateFilter = <function> defined @Interface/AddOns/AdiBags_Bears_Mining/core.lua:52
```

```
Message: Interface/AddOns/AdiBags_Bears_Mining/database.lua:1 (null)
Time: Sat Oct 29 14:57:37 2022
Count: 1
```

```
Message: Interface/AddOns/AdiBags_Bears_Mining/core.lua:1 (null)
Time: Sat Oct 29 14:57:37 2022
Count: 1
```

```
Message: Interface\FrameXML\Bindings.xml:1 Interface/AddOns/AdiBags_Bears_Mining/database.lua:1 (null)
Time: Sat Oct 29 14:57:37 2022
Count: 1
```

```
Message: Interface\FrameXML\Bindings.xml:1 Interface/AddOns/AdiBags_Bears_Mining/core.lua:1 (null)
Time: Sat Oct 29 14:57:37 2022
Count: 1
```

**Comment by N6REJ** [comment]
Can you see if there is another update please?
you should be on 2022.10.29.2

**Comment by rcharre** [comment]
No error anymore, thanks a lot !

**Comment by N6REJ** [comment]
yvw.  I'm going to close this ticket.  If you need more help just holler
