### ISSUE TITLE
Wago.io page for this addon downloads Adibags Bears Engineering, instead.

### ISSUE THREAD

**Issue by JeremyMorton** [N6REJ/AdiBags_Shadowlands_Mining#13]
On https://addons.wago.io/addons/adibags-bears-mining, clicking the Download button gives you AdiBags_Bears_Engineering-2022.10.29.1.zip and looking at the Releases page and clicking on the changelog icon for each release, some show the changelog for engineering releases and some show the changelog for mining releases.

**Comment by N6REJ** [comment]
ty for the report.  Somehow the id's for mining and engineering got mixed up on wago.  This has been corrected.
Version 2022.10.30 will be the corrected version And should be ready in 5-10 minutes.
